export const sponsrsData=[
    {
        img:'./images/sponsors/cspace.svg'
    },
    {
        img:'./images/sponsors/delever.svg'
    },
    {
        img:'./images/sponsors/fonon.svg'
    },
    {
        img:'./images/sponsors/hamkorbank.svg'
    },
    {
        img:'./images/sponsors/hoshimov.svg'
    },
    {
        img:'./images/sponsors/iman.svg'
    },
    {
        img:'./images/sponsors/akfaMedline.svg'
    },
]
export const sponsrsData2=[
    {
        img:'./images/sponsors/shefBurger.svg'
    },
    {
        img:'./images/sponsors/myTaxi.svg'
    },
    {
        img:'./images/sponsors/workly.svg'
    },
    {
        img:'./images/sponsors/rabota.svg'
    },
    {
        img:'./images/sponsors/gz.svg'
    },
    {
        img:'./images/sponsors/smsuz.svg'
    },
    {
        img:'./images/sponsors/maxtrack.svg'
    },
]